#!/bin/bash

v=${{ env.graalvm_version }}
f=graalvm-ce-java11-linux-amd64-$v.tar.gz
curl -O https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$v/$f
export GRAALVM=${{ github.workspace }}/graalvm
mkdir -pv $GRAALVM
tar xzf $fn -C $GRAALVM --strip-components 1
export PATH=$GRAALVM/bin:$PATH
gu install native-image
echo GRAALVM=$GRAALVM PATH=$PATH >>$GITHUB_ENV
rm -fv $f
