#!/bin/bash -eux

v=$(head -n1 src/version)
releases=/repos/maddenp/nml/releases

gh api $releases                            \
   -F draft=false                           \
   -F generate_release_notes=false          \
   -F prerelease=false                      \
   -H "Accept: application/vnd.github+json" \
   -X POST                                  \
   -f name=$v                               \
   -f tag_name=$v                           \
   -f target_commitish=master

pwd
ls
ls target
mv -v target/nml.jar .

for x in nml.jar; do # TODO add nml
  gh api $releases/$v/assets?name=$x          \
     -H "Accept: application/vnd.github+json" \
     -X POST                                  \
     -f "@$x"
done
