#!/bin/bash -eux

v=$(head -n1 src/version)
args=(
  -X POST
  -H "Accept: application/vnd.github+json"
  /repos/maddenp/nml/releases
  -F draft=false
  -F generate_release_notes=false
  -F prerelease=false
  -f name="$v"
  -f tag_name="$v"
  -f target_commitish="master"
)
gh api ${args[*]}
