name: ci
on:
  push:
    branches:
      - native
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Install Clojure
        run: |
          fn=linux-install-1.11.1.1208.sh
          curl -O https://download.clojure.org/install/$fn
          chmod +x $fn
          sudo ./$fn
      - name: Test
        run: make test

