name: ci
env:
  CLOJURE_VERSION: 1.11.1.1208
  GH_TOKEN: ${{ github.token }}
  GRAALVM_VERSION: 22.3.1
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check tag
        run:  .github/scripts/tag-check
      - name: Install GraalVM
        run: .github/scripts/install-graalvm
      - name: Install Clojure
        run: .github/scripts/install-clojure
      - name: Run tests
        run: make test
      - name: Build uberjar
        run: make uberjar
      - name: Build native executable
        run: make native
      - name: Check artifacts
        run: .github/scripts/artifact-checks
      - name: Tag
        run: .github/scripts/tag-create
      - name: Release
        run: .github/scripts/release
